#!/bin/bash

echo "🔑 Add SSH Key to nxgdevllc GitHub Account"
echo "=========================================="
echo ""
echo "✅ SSH key is ready: mp@nxgdev.com"
echo "❌ Key not yet added to GitHub"
echo ""
echo "📋 Steps to add the key:"
echo ""
echo "1. Go to: https://github.com/settings/keys"
echo "   (Make sure you're logged in as nxgdevllc)"
echo ""
echo "2. Click 'New SSH key'"
echo ""
echo "3. Title: Mac Mini - Development"
echo ""
echo "4. Key: Copy and paste this entire line:"
echo "   =========================================="
echo "   ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILk+b2GBP8HmxHhuNjtsBavsIL7wS9NVQCanwppVfvBV mp@nxgdev.com"
echo "   =========================================="
echo ""
echo "5. Click 'Add SSH key'"
echo ""
echo "6. After adding, test with:"
echo "   ssh -T git@github.com"
echo ""
echo "7. Then push your code:"
echo "   git push -u origin main"
echo ""
echo "🔗 Direct link: https://github.com/settings/keys" 