#!/bin/bash

echo "🔑 New SSH Key for nxgdevllc Account"
echo "===================================="
echo ""
echo "✅ New SSH key generated successfully!"
echo "📧 Email: mp@nxgdev.com"
echo ""
echo "📋 To add this key to your nxgdevllc GitHub account:"
echo ""
echo "1. Go to: https://github.com/settings/keys"
echo "   (Make sure you're logged in as nxgdevllc)"
echo ""
echo "2. Click 'New SSH key'"
echo ""
echo "3. Title: Mac Mini - nxgdevllc"
echo ""
echo "4. Key: Copy and paste this entire line:"
echo "   =========================================="
echo "   ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILk+b2GBP8HmxHhuNjtsBavsIL7wS9NVQCanwppVfvBV mp@nxgdev.com"
echo "   =========================================="
echo ""
echo "5. Click 'Add SSH key'"
echo ""
echo "6. After adding the key, test it with:"
echo "   ssh -T git@github.com-nxgdevllc"
echo ""
echo "7. Then update your repository remote:"
echo "   git remote set-url origin git@github.com-nxgdevllc:nxgdevllc/proj-spbr-booking.git"
echo ""
echo "8. Finally push your code:"
echo "   git push -u origin main"
echo ""
echo "🔗 Direct link to SSH keys:"
echo "https://github.com/settings/keys" 