#!/bin/bash

echo "🔧 GitHub Repository Access Options"
echo "==================================="
echo ""
echo "Current situation:"
echo "✅ You're authenticated as: lauxdcom"
echo "❌ Trying to push to: nxgdevllc/proj-spbr-booking"
echo ""
echo "📋 Choose one of these options:"
echo ""
echo "Option 1: Add SSH Key to nxgdevllc Account"
echo "1. Go to https://github.com/settings/keys (as nxgdevllc)"
echo "2. Add your SSH key:"
echo "   ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEM2ZDHf4lTCW3QZB/IDn1BA8c9d715FwN+kHU4u99I0 your_email@example.com"
echo "3. Then run: git remote set-url origin git@github.com:nxgdevllc/proj-spbr-booking.git"
echo "4. Then run: git push -u origin main"
echo ""
echo "Option 2: Use HTTPS with Personal Access Token"
echo "1. Go to https://github.com/settings/tokens (as nxgdevllc)"
echo "2. Generate new token with 'repo' permissions"
echo "3. Use the token as password when prompted"
echo "4. Run: git push -u origin main"
echo ""
echo "Option 3: Create New Repository Under lauxdcom"
echo "1. Go to https://github.com/new (as lauxdcom)"
echo "2. Create repository: spbr-booking"
echo "3. Run: git remote set-url origin git@github.com:lauxdcom/spbr-booking.git"
echo "4. Run: git push -u origin main"
echo ""
echo "🎯 Recommended: Option 1 (Add SSH key to nxgdevllc)" 