#!/bin/bash

echo "🔑 Supabase API Keys Setup"
echo "=========================="
echo ""
echo "✅ You already have:"
echo "   Project URL: https://agugyskqboencxrqquaw.supabase.co"
echo "   Anon Key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFndWd5c2txYm9lbmN4cnFxdWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTk0MDcsImV4cCI6MjA3MDEzNTQwN30.-H0tX5q0NZTPxiIhhvQyk3yjdtY1TqtnOmkJFUG1x7Q"
echo ""
echo "🔍 To get your Service Role Key:"
echo "1. Go to https://supabase.com/dashboard/project/agugyskqboencxrqquaw/settings/api"
echo "2. Copy the 'service_role' key (starts with eyJ...)"
echo "3. Add it to your .env.local file"
echo ""
echo "📝 Your .env.local should look like this:"
echo "=========================================="
echo "NEXT_PUBLIC_SUPABASE_URL=https://agugyskqboencxrqquaw.supabase.co"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFndWd5c2txYm9lbmN4cnFxdWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTk0MDcsImV4cCI6MjA3MDEzNTQwN30.-H0tX5q0NZTPxiIhhvQyk3yjdtY1TqtnOmkJFUG1x7Q"
echo "SUPABASE_SERVICE_ROLE_KEY=YOUR_SERVICE_ROLE_KEY_HERE"
echo "NEXT_PUBLIC_APP_URL=http://localhost:3000"
echo "NEXTAUTH_SECRET=your_nextauth_secret_key_here"
echo "NEXTAUTH_URL=http://localhost:3000"
echo ""
echo "🔗 Direct link to your Supabase API settings:"
echo "https://supabase.com/dashboard/project/agugyskqboencxrqquaw/settings/api" 